name: Haolan Chen
description: 
meta_description: "Haolan Chen"

markdown: redcarpet
pygments: true

baseurl: http://foolchan2556.github.io/

logo: false
paginate: 15
permalink: /:title


# Details for the RSS feed generator
url:            'foolchan2556.github.io'
author:         'Haolan Chen'


